# Generated by Django 4.2.28 on 2026-02-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(default='John Doe', max_length=200)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('carrier_name', models.CharField(default='ABC Trucking Co.', max_length=200)),
                ('carrier_dot', models.CharField(blank=True, max_length=20)),
                ('truck_number', models.CharField(default='T-1001', max_length=50)),
                ('trailer_number', models.CharField(blank=True, max_length=50)),
                ('home_terminal', models.CharField(blank=True, max_length=200)),
                ('cycle_rule', models.CharField(default='70hr/8day', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=300)),
                ('pickup_location', models.CharField(max_length=300)),
                ('dropoff_location', models.CharField(max_length=300)),
                ('current_cycle_used', models.FloatField(default=0)),
                ('current_lat', models.FloatField(blank=True, null=True)),
                ('current_lng', models.FloatField(blank=True, null=True)),
                ('pickup_lat', models.FloatField(blank=True, null=True)),
                ('pickup_lng', models.FloatField(blank=True, null=True)),
                ('dropoff_lat', models.FloatField(blank=True, null=True)),
                ('dropoff_lng', models.FloatField(blank=True, null=True)),
                ('total_distance', models.FloatField(blank=True, null=True)),
                ('estimated_driving_hours', models.FloatField(blank=True, null=True)),
                ('total_days', models.IntegerField(blank=True, null=True)),
                ('fuel_stops', models.IntegerField(blank=True, null=True)),
                ('remaining_cycle_hours', models.FloatField(blank=True, null=True)),
                ('route_data', models.TextField(blank=True, default='[]')),
                ('stops_data', models.TextField(blank=True, default='[]')),
                ('timeline_data', models.TextField(blank=True, default='[]')),
                ('log_sheets_data', models.TextField(blank=True, default='[]')),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('completed', 'Completed')], default='planning', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
